### PR TITLE
Enable pylint autopep8

### PR DESCRIPTION
**Pull request by frascuchon**
This PR includes some code checks and auto fixing with pylint and autopep8.

I have no experience with python code quality tooling so, please, if you have suggestions, please let me known

### CODE REVIEW

**Comment by dcfidalgo** [comment]
Regarding autopep8: I think [black](https://github.com/psf/black) is not bad and we have been using it so far. So i would stick with it.
Regarding pylint: :+1: to include it in our CIs, so maybe i would move it to the `make test` call

**Comment by frascuchon** [comment]
> Regarding autopep8: I think [black](https://github.com/psf/black) is not bad and we have been using it so far. So i would stick with it.
> Regarding pylint: 👍 to include it in our CIs, so maybe i would move it to the `make test` call

There are some problems between black code formatting and pylint checks. See [here](https://github.com/psf/black/issues/48) but I think we can disable some pylint rules.

The `make test` directive first call the `make check` so we'll check the code quality before running tests

**Comment by dcfidalgo** [comment]
Ok, then i would go for disabling this specific check in pylint (seems to be indentation)

**Comment by dvsrepo** [comment]
> Ok, then i would go for disabling this specific check in pylint (seems to be indentation)

👍

**Review by dvsrepo — APPROVED** [review]

**Pull request merged**
